version: '3.9' # optional since v1.27.0
services:
  thesis-db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - '3306:3306'
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
#     networks:
#       - mynet

  thesis-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '4200:4200'
    volumes:
      - ./frontend/src:/frontend/src
    # networks:
    #   - mynet

  thesis-backend:
    depends_on:
      - thesis-db
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: thesis-db
      SESSION_SECRET: ${SESSION_SECRET}
      FRONT_END_IP: ${FRONT_END_IP}
      PROXY_IP: ${PROXY_IP}
    volumes:
      - ./backend:/backend
    # networks:
    #   - host
      
  thesis-phpmyadmin:
    depends_on:
      - thesis-db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '5001:80'
    env_file: ./.env
    environment:
      PMA_HOST: thesis-db 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#     networks:
#       - mynet

  thesis-json:
    build:
      context: frontend/json-server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    restart: unless-stopped
    volumes:
      - ./frontend/json-server:/json-server
    # networks:
    #   - mynet
      
volumes:
  db_data: 

# bridge network is the default one 
# networks:
#   mynet:
#     driver: bridge